updates javascript intro challenges
LEARNAcademy/Instructor-Resources pull request #1
Opened 2022-01-18 17:11 UTC by elysemontano

updates javascript intro challenges to show code examples and outputs.

2022-01-18 23:46 UTC, sjproctor requested changes
Just a small fix!

2022-01-18 23:46 UTC, sjproctor commented on javascript/intro.md
> +console.log("The answer to " + theQuestion + " is " + theAnswer)  // => The answer to life, the universe, and everything is 42
Pop this "The answer to life, the universe, and everything is 42" and this "the universe" into strings.

2022-01-19 00:43 UTC, elysemontano commented on javascript/intro.md
> +console.log("The answer to " + theQuestion + " is " + theAnswer)  // => The answer to life, the universe, and everything is 42
Not sure I follow...  "life, the universe, and everything" are already strings in a variable and was being asked to concatenate the variables.  I added the strings "the answer to " and " is " to make it a full sentence.  Did you want these set as variables too?

2022-01-19 18:17 UTC, sjproctor approved these changes
Fabulous!

2022-01-19 19:39 UTC, merged