updated challenges with solutions
LEARNAcademy/Instructor-Resources pull request #10
Opened 2022-01-31 19:18 UTC by SunkissedQueen

2022-02-01 02:15 UTC, sjproctor requested changes
Woohoo! Looks really good. Just a couple really small fixes.

2022-02-01 02:15 UTC, sjproctor commented on javascript/jest.md
> +  }
Couple spacing issues here on lines 467 and 470.

2022-02-01 02:15 UTC, sjproctor commented on javascript/jest.md
> +    if(string === "apple") {
This can be one conditional statement with only one `if` and the rest `else if`

2022-02-01 02:15 UTC, sjproctor commented on javascript/jest.md
> +}
Couple spaces here too: `(number % 2 !== 0)`

2022-02-01 02:15 UTC, sjproctor commented on javascript/jest.md
> +    it("akes two numbers as arguments and returns whether the first number is evenly divisible by the second", () => {
small typo in your `it` statement

2022-02-01 07:45 UTC, SunkissedQueen commented on javascript/jest.md
> +    it("akes two numbers as arguments and returns whether the first number is evenly divisible by the second", () => {
"t" has been located.

2022-02-01 07:45 UTC, SunkissedQueen commented on javascript/jest.md
> +}
Spaces have been added

2022-02-01 07:45 UTC, SunkissedQueen commented on javascript/jest.md
> +    if(string === "apple") {
Wow. I definitely meant to put else if...copy and paste and forgot. I corrected the issue.

2022-02-01 07:45 UTC, SunkissedQueen commented on javascript/jest.md
> +  }
Modulo and I will act right one day. Corrected the spacing

2022-02-02 19:44 UTC, sjproctor approved these changes
Looks great!

2022-02-03 01:42 UTC, merged