updates javascript classes challenges
LEARNAcademy/Instructor-Resources pull request #11
Opened 2022-01-31 19:48 UTC by elysemontano

updates javascript classes challenges

2022-02-01 02:19 UTC, sjproctor requested changes
Beautiful! This section looks great. Just a couple very tiny things.

2022-02-01 02:19 UTC, sjproctor commented on javascript/classes.md
> +``` java
Is this a coffee joke? haha

2022-02-01 02:19 UTC, sjproctor commented on javascript/classes.md
> +}
Small typo in espresso

2022-02-03 17:59 UTC, elysemontano commented on javascript/classes.md
> +``` java
🤣  unintentionally yes!

2022-02-03 19:18 UTC, sjproctor approved these changes
Beautiful!

2022-02-03 19:28 UTC, merged