Js intro hof charlean
LEARNAcademy/Instructor-Resources pull request #12
Opened 2022-01-31 20:05 UTC by SunkissedQueen

2022-02-01 02:27 UTC, sjproctor requested changes
Looks awesome. Mostly just a few syntax things on the outputs.

2022-02-01 02:27 UTC, sjproctor commented on javascript/higher-order-functions.md
> +  // Output: [ 30, 90, 150, 40, 100 ]
Couple extra spaces around the brackets on 208.

2022-02-01 02:27 UTC, sjproctor commented on javascript/higher-order-functions.md
> +  // Output: [ 7, 3, 5, 13 ]
Same thing here. Should be `[7, 3, 5, 13]`

2022-02-01 02:27 UTC, sjproctor commented on javascript/higher-order-functions.md
> +    // return the local variable joined into a string with no spaces
string should be in double quotes and line 235 should be moved out to line up with line 232

2022-02-01 02:27 UTC, sjproctor commented on javascript/higher-order-functions.md
> +      return Boolean(value) === true
ooooooh that is clever!

2022-02-01 02:27 UTC, sjproctor commented on javascript/higher-order-functions.md
> +  // Output: [ 58, 'abcd', true ]
There are extra spaces and single quotes on line 260

2022-02-01 02:27 UTC, sjproctor commented on javascript/higher-order-functions.md
> +    return newArray
I love the indexOf approach. This might be a good opportunity to pass in the third argument to `.filter`
```
return array3.filter((value, index, array) => array.indexOf(value) === index)
```

2022-02-01 06:33 UTC, SunkissedQueen commented on javascript/higher-order-functions.md
> +    // return the local variable joined into a string with no spaces
string annotated with double quotes and code block properly aligned

2022-02-01 07:29 UTC, SunkissedQueen commented on javascript/higher-order-functions.md
> +    return newArray
Cool. Keep it DRY. Thanks. I have updated the function as recommended.

2022-02-01 07:29 UTC, SunkissedQueen commented on javascript/higher-order-functions.md
> +  // Output: [ 58, 'abcd', true ]
Copying the terminal again. I took out the spaces and added double quotes

2022-02-01 07:29 UTC, SunkissedQueen commented on javascript/higher-order-functions.md
> +      return Boolean(value) === true
Thank you. My brain has been trained by the best.

2022-02-01 07:29 UTC, SunkissedQueen commented on javascript/higher-order-functions.md
> +  // Output: [ 7, 3, 5, 13 ]
Spaces removed.

2022-02-01 07:29 UTC, SunkissedQueen commented on javascript/higher-order-functions.md
> +  // Output: [ 30, 90, 150, 40, 100 ]
Ok. I will remove spaces. I copied  the output directly from the terminal.

2022-02-02 19:41 UTC, sjproctor approved these changes
Wonderful!

2022-02-03 01:41 UTC, merged