Fixed: few syntax errors.  Added: first 4 challenges
LEARNAcademy/Instructor-Resources pull request #15
Opened 2022-02-08 01:27 UTC by halebeau

Found a few syntax errors in the comments. Got thru the first 4 challenges.  Reviewed the resources

2022-02-08 03:34 UTC, sjproctor requested changes

2022-02-08 03:34 UTC, sjproctor commented on ruby/methods.md
> +```ruby
This actually isn't Ruby code. It is from the command line. So it would be "bash"

2022-02-08 03:34 UTC, sjproctor commented on ruby/methods.md
> +
Based on the prompt we are looking for just a true or false output.

2022-02-08 03:34 UTC, sjproctor commented on ruby/methods.md
> +
Same thing here. The output should match the given prompt.

2022-02-08 03:34 UTC, sjproctor commented on ruby/methods.md
> +def palindrome? string
I'm very interested in where you found the syntax for naming this method. A bunch of the echo students did the exact same thing. It is not a good practice to include a question mark on your method name.

2022-02-10 02:27 UTC, sjproctor requested changes

2022-02-10 02:27 UTC, sjproctor commented on ruby/methods.md
> +    p true
It is best practice for the `p` to be on the function invocation not on the inner workings of the function.

2022-02-10 02:27 UTC, sjproctor commented on ruby/methods.md
> +    p 'Invalid'
Same thing here, the `p` should be on the invocation.

2022-02-10 02:27 UTC, sjproctor commented on ruby/methods.md
> +    puts 'User ID and password cannot be the same.'
Same thing here with the `puts`. It should be on the invocation.

2022-02-10 02:27 UTC, sjproctor commented on ruby/methods.md
> +  elsif password == 'password' || password == 'Password'
I don't think you will ever get to this line as the one before it will be true if the password is `password`.

2022-02-23 03:46 UTC, sjproctor requested changes
Couple small things to clean up.

2022-02-23 03:46 UTC, sjproctor commented on ruby/methods.md
> +p sum_these_numbers -15, 30
It would be a best practice to use parens on the invocation of the method.

2022-02-24 21:07 UTC, halebeau commented
Changed "puts" to "p".
Added parens to values

2022-02-27 21:26 UTC, sjproctor requested changes
I had trouble seeing the changes of the last update pushed on this view. I left comments on the actual commit. The only feedback is that Ruby is really picky about spaces. You will need to remove the space between the function invocation and the parentheses.

2022-03-01 22:41 UTC, sjproctor approved these changes
yay!

2022-03-07 22:17 UTC, merged