loops challenge  md update
LEARNAcademy/Instructor-Resources pull request #3
Opened 2022-01-21 22:07 UTC by halebeau

Loops challenge md update

2022-01-24 23:09 UTC, sjproctor requested changes
Can you change the format so that the entire section is a code snippet? Check this for reference: https://github.com/LEARNAcademy/Instructor-Resources/blob/main/javascript/arrays.md#challenges
Also noting the `// output: ` notation. The spacing around your curlies looks great!

2022-01-27 18:32 UTC, halebeau commented
Made revisions from last request. My second push

2022-01-27 20:19 UTC, sjproctor requested changes
Looking better! Few more things to clean up. And please double check all the indentations. It seems to range from 4 spaces to a single space. Every indentation should be two spaces.

2022-01-27 20:19 UTC, sjproctor commented on javascript/loops.md
> +   console.log(i * 3);
Can you remove the semi colon here?

2022-01-27 20:19 UTC, sjproctor commented on javascript/loops.md
> +
Looks like 4 spaces in the `if` statement, should be 2.
Remove -->> and replace with a `:`

2022-01-27 20:19 UTC, sjproctor commented on javascript/loops.md
> +const highest = nums[0]
`-->` can be removed from line 160
Comment out line 161

2022-01-27 20:19 UTC, sjproctor commented on javascript/loops.md
> +<!-- 1. Even or Odd: Write a for loop that iterates from 0 to 15. For each iteration, it will check if the current number is odd or even, and display the appropriate outcome. **Expected output** -> "
This can be moved into the JS code block and commented out.

2022-01-27 20:19 UTC, sjproctor commented on javascript/loops.md
> +// output: "0 is even", "1 is odd", "2 is even", ...etc
Can you use string interpolation here instead please.

2022-01-27 20:19 UTC, sjproctor commented on javascript/loops.md
> +let letterE = 0
This variable name seems a little confusing. Maybe something like `letterECount` or `occurenceOfE`

2022-02-01 01:11 UTC, sjproctor requested changes
Most of the code still have 4 spaces.

2022-02-01 01:11 UTC, sjproctor commented on javascript/loops.md
> +
Still 4 spaces here.

2022-02-02 17:45 UTC, halebeau commented
Sarah i am confused. My last push has all this fixed including the newest request. I am using 2 tabs for indentation = 4 space bars. Should 1 tab = 1 spacebar?  On my push, line 155 has 2 tabs.

2022-02-02 18:03 UTC, sjproctor commented
A tab should consist of two spaces. Each indentation is one tab.

```
for(let i = 0; i <= 20; i++) {
  console.log(i * 3)
} 
```

2022-02-02 18:29 UTC, halebeau commented
Awesome, thanks for confirming.  When u get the chance we can review it together.

2022-02-02 18:52 UTC, sjproctor requested changes
Still 4 spaces on most of the code. It might be a good idea to "untab" everything over all the way to the left (shift + tab) and then tab each line individually.

2022-02-02 18:52 UTC, sjproctor commented on javascript/loops.md
> +}
2/2: Still has 4 spaces here.

2022-02-02 18:52 UTC, sjproctor commented on javascript/loops.md
> +//1. Even or Odd: Write a for loop that iterates from 0 to 15. For each iteration, it will check if the current number is odd or even, and display the appropriate outcome. **Expected output** -> "0 i
2/2: Line 200 can be commented out.

2022-02-02 19:57 UTC, sjproctor approved these changes

2022-02-02 19:58 UTC, merged