updated the challenge and stretch challenges with solutions
LEARNAcademy/Instructor-Resources pull request #4
Opened 2022-01-24 18:05 UTC by SunkissedQueen

Updated the functions.md with solutions

2022-01-24 23:44 UTC, sjproctor requested changes
Mainly just some nitpicking notes about spaces. Few other comments to consider.

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +      if(num3%num4 === 0) {
Can you add spaces around your modulo operator please!

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +    // Output: "16 is not evenly divisible by 3"
And a spaces after the comma before the second argument.

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +      // use operators (relational, conditional) and length property of each string to determine which string has the most characters
A space after the => before the {

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +    const greaterNum = (num5, num6) => {
I think making the variables num1 and num2 may make sense in the individual context of this problem.

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +        if(lang == "fr") {
Can the equality operators be `===` instead of `==` please

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +        return number + " " + noun + "s"
I think string interpolation might be useful here.

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +  // ```javascript
Can you remove the markdown notation that is wrapping these variables?

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +      // use conditional, loose equality, and logical operators to evaluate number and noun
I am curious about the choice to use loose equality here. Can you give me more context?

2022-01-24 23:44 UTC, sjproctor commented on javascript/functions.md
> +        return "Hello World!"
I think this will work as a catch all, but the idea is to give the parameter a value that can be evaluated even if no argument is passed. 
```
  } else if(code === "en") {
    return "Hello world"
  }
console.log(helloWorld2())
```

2022-01-25 03:08 UTC, SunkissedQueen commented on javascript/functions.md
> +      if(num3%num4 === 0) {
Yes, I shall add spaces to all instances of modulo. This task has been completed.

2022-01-25 03:08 UTC, SunkissedQueen commented on javascript/functions.md
> +    // Output: "16 is not evenly divisible by 3"
Reviewed all arguments and added spaces as needed

2022-01-25 03:08 UTC, SunkissedQueen commented on javascript/functions.md
> +      // use operators (relational, conditional) and length property of each string to determine which string has the most characters
Gave the arrow syntax its space

2022-01-25 03:08 UTC, SunkissedQueen commented on javascript/functions.md
> +    const greaterNum = (num5, num6) => {
The arguments are num1 and num2 in the cases that I had two number variables

2022-01-25 03:08 UTC, SunkissedQueen commented on javascript/functions.md
> +        if(lang == "fr") {
Switched my loose equality conditions to strict

2022-01-25 03:10 UTC, SunkissedQueen commented on javascript/functions.md
> +        return number + " " + noun + "s"
Switched to string interpolation on the stretch challenges. I also updated the isLonger function not to use string interpolation since I just needed to return the variable

2022-01-25 03:10 UTC, SunkissedQueen commented on javascript/functions.md
> +  // ```javascript
Yes, I wasn't sure if I had to keep it because it was already on the challenge. It was disturbing my eyes. I happily removed that notation.

2022-01-25 03:12 UTC, SunkissedQueen commented on javascript/functions.md
> +      // use conditional, loose equality, and logical operators to evaluate number and noun
I can see the error in my thought process...because I was thinking if a noun is inputted without quotations the noun could still be accepted. This is a string and needs quotations to make it as such. I have switched my loose equality to strict in all the challenges.

2022-01-25 03:16 UTC, SunkissedQueen commented on javascript/functions.md
> +        return "Hello World!"
My interpretation of passing a default parameters was to start the function similar to the syntax from this link on the challenge.   
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

From the link
`function multiply(a, b = 1) {
  return a * b;
}`  

My interpretation 
`const helloWorld2 = (lang = "en") => {
return "Hello World!"
        }`
        
Then I began to add the stringent properties with if/else if before the return for the default parameter.  I saw that the else statement and return do the same job with or without the established default value as an argument. Ending with the else if "en" conditional gives the default code if the function is called without an input `console.log(helloWorld2())`; however, it gives an `undefined` when inputting a language code not listed. 
       
I made an else statement to give the Hello World! in English which covers any other language code. Just to give consistency with the conditionals. Or should I just keep the standalone return statement?

2022-01-25 18:07 UTC, sjproctor requested changes
Yay! Beautiful. Just one more little change and we should be all set.

2022-01-25 18:07 UTC, sjproctor commented on javascript/functions.md
> +      if(number != 1) {
Can you make the `!=` a `!==` in both pluralizer functions please!

2022-01-25 22:43 UTC, SunkissedQueen commented on javascript/functions.md
> +      if(number != 1) {
Updated. I went through again because it look like I unintentionally changed some text.

2022-01-26 16:01 UTC, sjproctor approved these changes
Yay beautiful!

2022-01-26 17:33 UTC, SunkissedQueen commented
I am so excited to press this merge pull request. I am contributing to the learn experience. Thank you for this opportunity.

2022-01-26 17:34 UTC, merged