snippets and settings for vscode
LEARNAcademy/Instructor-Resources pull request #7
Opened 2022-01-27 23:06 UTC by WalkerTexas-coder

2022-01-27 23:14 UTC, sjproctor requested changes
Couple notes for your review.

2022-01-27 23:14 UTC, sjproctor commented on tools-and-resources/vscode-snippets-settings.md
> +5. save file
Prolly capitalize Save to be consistent.

2022-01-27 23:14 UTC, sjproctor commented on tools-and-resources/vscode-snippets-settings.md
> +		"body": "conslone.log($1)",
Still have the typo here

2022-01-27 23:14 UTC, sjproctor commented on tools-and-resources/vscode-snippets-settings.md
> +		],
I think we decided on `for(let i = 0; i < array.length; i++) {"` - no spaces around the content in the parens but a space after the closing paren before the opening curly.

2022-01-27 23:14 UTC, sjproctor commented on tools-and-resources/vscode-snippets-settings.md
> +    "description": "If Statement"
I can't tell for sure but make sure there are no spaces around the condition `if(${1:condition})`

2022-01-27 23:15 UTC, WalkerTexas-coder commented on tools-and-resources/vscode-snippets-settings.md
> +		"body": "conslone.log($1)",
hhhhmm that's weird

2022-01-28 00:39 UTC, sjproctor approved these changes
Great!

2022-01-28 00:39 UTC, sjproctor commented on tools-and-resources/vscode-snippets-settings.md
> +		],
WOOO!

2022-01-28 00:42 UTC, merged