updates challenges
LEARNAcademy/Instructor-Resources pull request #8
Opened 2022-01-28 17:18 UTC by elysemontano

updates challenge section with code blocks

2022-02-01 02:01 UTC, sjproctor requested changes
Great job! Logic looks awesome overall. Couple of overall things. Can you run through the tabbing? Most indentation looks to be 4 spaces and some are even more. And there are a lot of double comments particularly on the outputs: `// // Output: 180300` can you remove any unnecessary characters?

2022-02-03 19:24 UTC, sjproctor requested changes
As mentioned in a comment, sometimes the GitHub UI creates an odd display. But on about 4 of the problems there seems to be a whole bunch of extra spaces. Will you just double check? If it looks good on your end then I will approve.

2022-02-03 19:24 UTC, sjproctor commented on javascript/functions-loops-arrays.md
> +	return stringArray.join("")
It might be the GitHub UI, but there seems to be a whole lot of extra spaces here. Will you double check this? If it looks good on your end then I am good.

2022-02-03 19:24 UTC, sjproctor commented on javascript/functions-loops-arrays.md
> +  return sum
Same thing with the spaces here.

2022-02-03 19:37 UTC, elysemontano commented on javascript/functions-loops-arrays.md
> +	return stringArray.join("")
When I am in my text editor, the spacing looks correct.  If I open preview though I am seeing some weird spacing as well.  So weird!

2022-02-03 22:04 UTC, sjproctor approved these changes
Well let's send it and if it needs additional editing we can work from there.

2022-02-03 22:12 UTC, merged